// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go-swagger/models"
)

// DeleteUsersUserIDCreatedCode is the HTTP code returned for type DeleteUsersUserIDCreated
const DeleteUsersUserIDCreatedCode int = 201

/*
DeleteUsersUserIDCreated Created

swagger:response deleteUsersUserIdCreated
*/
type DeleteUsersUserIDCreated struct {

	/*
	  In: Body
	*/
	Payload *models.MainUser `json:"body,omitempty"`
}

// NewDeleteUsersUserIDCreated creates DeleteUsersUserIDCreated with default headers values
func NewDeleteUsersUserIDCreated() *DeleteUsersUserIDCreated {

	return &DeleteUsersUserIDCreated{}
}

// WithPayload adds the payload to the delete users user Id created response
func (o *DeleteUsersUserIDCreated) WithPayload(payload *models.MainUser) *DeleteUsersUserIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users user Id created response
func (o *DeleteUsersUserIDCreated) SetPayload(payload *models.MainUser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersUserIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersUserIDBadRequestCode is the HTTP code returned for type DeleteUsersUserIDBadRequest
const DeleteUsersUserIDBadRequestCode int = 400

/*
DeleteUsersUserIDBadRequest Bad Request

swagger:response deleteUsersUserIdBadRequest
*/
type DeleteUsersUserIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewDeleteUsersUserIDBadRequest creates DeleteUsersUserIDBadRequest with default headers values
func NewDeleteUsersUserIDBadRequest() *DeleteUsersUserIDBadRequest {

	return &DeleteUsersUserIDBadRequest{}
}

// WithPayload adds the payload to the delete users user Id bad request response
func (o *DeleteUsersUserIDBadRequest) WithPayload(payload *models.MainErrorResponse) *DeleteUsersUserIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users user Id bad request response
func (o *DeleteUsersUserIDBadRequest) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersUserIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
