// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go-swagger/models"
)

// GetUsersUserIDOKCode is the HTTP code returned for type GetUsersUserIDOK
const GetUsersUserIDOKCode int = 200

/*
GetUsersUserIDOK OK

swagger:response getUsersUserIdOK
*/
type GetUsersUserIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.MainUser `json:"body,omitempty"`
}

// NewGetUsersUserIDOK creates GetUsersUserIDOK with default headers values
func NewGetUsersUserIDOK() *GetUsersUserIDOK {

	return &GetUsersUserIDOK{}
}

// WithPayload adds the payload to the get users user Id o k response
func (o *GetUsersUserIDOK) WithPayload(payload *models.MainUser) *GetUsersUserIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users user Id o k response
func (o *GetUsersUserIDOK) SetPayload(payload *models.MainUser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersUserIDBadRequestCode is the HTTP code returned for type GetUsersUserIDBadRequest
const GetUsersUserIDBadRequestCode int = 400

/*
GetUsersUserIDBadRequest Bad Request

swagger:response getUsersUserIdBadRequest
*/
type GetUsersUserIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewGetUsersUserIDBadRequest creates GetUsersUserIDBadRequest with default headers values
func NewGetUsersUserIDBadRequest() *GetUsersUserIDBadRequest {

	return &GetUsersUserIDBadRequest{}
}

// WithPayload adds the payload to the get users user Id bad request response
func (o *GetUsersUserIDBadRequest) WithPayload(payload *models.MainErrorResponse) *GetUsersUserIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users user Id bad request response
func (o *GetUsersUserIDBadRequest) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUserIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersUserIDNotFoundCode is the HTTP code returned for type GetUsersUserIDNotFound
const GetUsersUserIDNotFoundCode int = 404

/*
GetUsersUserIDNotFound Not Found

swagger:response getUsersUserIdNotFound
*/
type GetUsersUserIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewGetUsersUserIDNotFound creates GetUsersUserIDNotFound with default headers values
func NewGetUsersUserIDNotFound() *GetUsersUserIDNotFound {

	return &GetUsersUserIDNotFound{}
}

// WithPayload adds the payload to the get users user Id not found response
func (o *GetUsersUserIDNotFound) WithPayload(payload *models.MainErrorResponse) *GetUsersUserIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users user Id not found response
func (o *GetUsersUserIDNotFound) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUserIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersUserIDUnprocessableEntityCode is the HTTP code returned for type GetUsersUserIDUnprocessableEntity
const GetUsersUserIDUnprocessableEntityCode int = 422

/*
GetUsersUserIDUnprocessableEntity Unprocessable Entity

swagger:response getUsersUserIdUnprocessableEntity
*/
type GetUsersUserIDUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewGetUsersUserIDUnprocessableEntity creates GetUsersUserIDUnprocessableEntity with default headers values
func NewGetUsersUserIDUnprocessableEntity() *GetUsersUserIDUnprocessableEntity {

	return &GetUsersUserIDUnprocessableEntity{}
}

// WithPayload adds the payload to the get users user Id unprocessable entity response
func (o *GetUsersUserIDUnprocessableEntity) WithPayload(payload *models.MainErrorResponse) *GetUsersUserIDUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users user Id unprocessable entity response
func (o *GetUsersUserIDUnprocessableEntity) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUserIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
