// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go-swagger/models"
)

// PostUsersCreatedCode is the HTTP code returned for type PostUsersCreated
const PostUsersCreatedCode int = 201

/*
PostUsersCreated Created

swagger:response postUsersCreated
*/
type PostUsersCreated struct {

	/*
	  In: Body
	*/
	Payload *models.MainUser `json:"body,omitempty"`
}

// NewPostUsersCreated creates PostUsersCreated with default headers values
func NewPostUsersCreated() *PostUsersCreated {

	return &PostUsersCreated{}
}

// WithPayload adds the payload to the post users created response
func (o *PostUsersCreated) WithPayload(payload *models.MainUser) *PostUsersCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users created response
func (o *PostUsersCreated) SetPayload(payload *models.MainUser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersBadRequestCode is the HTTP code returned for type PostUsersBadRequest
const PostUsersBadRequestCode int = 400

/*
PostUsersBadRequest Bad Request

swagger:response postUsersBadRequest
*/
type PostUsersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewPostUsersBadRequest creates PostUsersBadRequest with default headers values
func NewPostUsersBadRequest() *PostUsersBadRequest {

	return &PostUsersBadRequest{}
}

// WithPayload adds the payload to the post users bad request response
func (o *PostUsersBadRequest) WithPayload(payload *models.MainErrorResponse) *PostUsersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users bad request response
func (o *PostUsersBadRequest) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersUnprocessableEntityCode is the HTTP code returned for type PostUsersUnprocessableEntity
const PostUsersUnprocessableEntityCode int = 422

/*
PostUsersUnprocessableEntity Unprocessable Entity

swagger:response postUsersUnprocessableEntity
*/
type PostUsersUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.MainErrorResponse `json:"body,omitempty"`
}

// NewPostUsersUnprocessableEntity creates PostUsersUnprocessableEntity with default headers values
func NewPostUsersUnprocessableEntity() *PostUsersUnprocessableEntity {

	return &PostUsersUnprocessableEntity{}
}

// WithPayload adds the payload to the post users unprocessable entity response
func (o *PostUsersUnprocessableEntity) WithPayload(payload *models.MainErrorResponse) *PostUsersUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users unprocessable entity response
func (o *PostUsersUnprocessableEntity) SetPayload(payload *models.MainErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
