// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Golang Swagger API Document
//
//	API Document practice
//	Terms Of Service:
//	  Document content
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: version1.0
//	License: license http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: API supporter<support@swagger.io> http://www.swagger.io/support
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
