// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-swagger/models"
)

// DeleteUsersUserIDReader is a Reader for the DeleteUsersUserID structure.
type DeleteUsersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteUsersUserIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteUsersUserIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUsersUserIDCreated creates a DeleteUsersUserIDCreated with default headers values
func NewDeleteUsersUserIDCreated() *DeleteUsersUserIDCreated {
	return &DeleteUsersUserIDCreated{}
}

/*
DeleteUsersUserIDCreated describes a response with status code 201, with default header values.

Created
*/
type DeleteUsersUserIDCreated struct {
	Payload *models.MainUser
}

// IsSuccess returns true when this delete users user Id created response has a 2xx status code
func (o *DeleteUsersUserIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete users user Id created response has a 3xx status code
func (o *DeleteUsersUserIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users user Id created response has a 4xx status code
func (o *DeleteUsersUserIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users user Id created response has a 5xx status code
func (o *DeleteUsersUserIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users user Id created response a status code equal to that given
func (o *DeleteUsersUserIDCreated) IsCode(code int) bool {
	return code == 201
}

func (o *DeleteUsersUserIDCreated) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}][%d] deleteUsersUserIdCreated  %+v", 201, o.Payload)
}

func (o *DeleteUsersUserIDCreated) String() string {
	return fmt.Sprintf("[DELETE /users/{user_id}][%d] deleteUsersUserIdCreated  %+v", 201, o.Payload)
}

func (o *DeleteUsersUserIDCreated) GetPayload() *models.MainUser {
	return o.Payload
}

func (o *DeleteUsersUserIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MainUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersUserIDBadRequest creates a DeleteUsersUserIDBadRequest with default headers values
func NewDeleteUsersUserIDBadRequest() *DeleteUsersUserIDBadRequest {
	return &DeleteUsersUserIDBadRequest{}
}

/*
DeleteUsersUserIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteUsersUserIDBadRequest struct {
	Payload *models.MainErrorResponse
}

// IsSuccess returns true when this delete users user Id bad request response has a 2xx status code
func (o *DeleteUsersUserIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users user Id bad request response has a 3xx status code
func (o *DeleteUsersUserIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users user Id bad request response has a 4xx status code
func (o *DeleteUsersUserIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete users user Id bad request response has a 5xx status code
func (o *DeleteUsersUserIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users user Id bad request response a status code equal to that given
func (o *DeleteUsersUserIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteUsersUserIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}][%d] deleteUsersUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteUsersUserIDBadRequest) String() string {
	return fmt.Sprintf("[DELETE /users/{user_id}][%d] deleteUsersUserIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteUsersUserIDBadRequest) GetPayload() *models.MainErrorResponse {
	return o.Payload
}

func (o *DeleteUsersUserIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MainErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
