// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-swagger/models"
)

// PostUsersReader is a Reader for the PostUsers structure.
type PostUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostUsersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewPostUsersUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostUsersCreated creates a PostUsersCreated with default headers values
func NewPostUsersCreated() *PostUsersCreated {
	return &PostUsersCreated{}
}

/*
PostUsersCreated describes a response with status code 201, with default header values.

Created
*/
type PostUsersCreated struct {
	Payload *models.MainUser
}

// IsSuccess returns true when this post users created response has a 2xx status code
func (o *PostUsersCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post users created response has a 3xx status code
func (o *PostUsersCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post users created response has a 4xx status code
func (o *PostUsersCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post users created response has a 5xx status code
func (o *PostUsersCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post users created response a status code equal to that given
func (o *PostUsersCreated) IsCode(code int) bool {
	return code == 201
}

func (o *PostUsersCreated) Error() string {
	return fmt.Sprintf("[POST /users][%d] postUsersCreated  %+v", 201, o.Payload)
}

func (o *PostUsersCreated) String() string {
	return fmt.Sprintf("[POST /users][%d] postUsersCreated  %+v", 201, o.Payload)
}

func (o *PostUsersCreated) GetPayload() *models.MainUser {
	return o.Payload
}

func (o *PostUsersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MainUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUsersBadRequest creates a PostUsersBadRequest with default headers values
func NewPostUsersBadRequest() *PostUsersBadRequest {
	return &PostUsersBadRequest{}
}

/*
PostUsersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostUsersBadRequest struct {
	Payload *models.MainErrorResponse
}

// IsSuccess returns true when this post users bad request response has a 2xx status code
func (o *PostUsersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post users bad request response has a 3xx status code
func (o *PostUsersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post users bad request response has a 4xx status code
func (o *PostUsersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post users bad request response has a 5xx status code
func (o *PostUsersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post users bad request response a status code equal to that given
func (o *PostUsersBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *PostUsersBadRequest) Error() string {
	return fmt.Sprintf("[POST /users][%d] postUsersBadRequest  %+v", 400, o.Payload)
}

func (o *PostUsersBadRequest) String() string {
	return fmt.Sprintf("[POST /users][%d] postUsersBadRequest  %+v", 400, o.Payload)
}

func (o *PostUsersBadRequest) GetPayload() *models.MainErrorResponse {
	return o.Payload
}

func (o *PostUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MainErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUsersUnprocessableEntity creates a PostUsersUnprocessableEntity with default headers values
func NewPostUsersUnprocessableEntity() *PostUsersUnprocessableEntity {
	return &PostUsersUnprocessableEntity{}
}

/*
PostUsersUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type PostUsersUnprocessableEntity struct {
	Payload *models.MainErrorResponse
}

// IsSuccess returns true when this post users unprocessable entity response has a 2xx status code
func (o *PostUsersUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post users unprocessable entity response has a 3xx status code
func (o *PostUsersUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post users unprocessable entity response has a 4xx status code
func (o *PostUsersUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this post users unprocessable entity response has a 5xx status code
func (o *PostUsersUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this post users unprocessable entity response a status code equal to that given
func (o *PostUsersUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *PostUsersUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /users][%d] postUsersUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostUsersUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /users][%d] postUsersUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostUsersUnprocessableEntity) GetPayload() *models.MainErrorResponse {
	return o.Payload
}

func (o *PostUsersUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MainErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
