basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API supporter
    url: http://www.swagger.io/support
  description: API Document practice
  license:
    name: license
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: Document content
  title: Golang Swagger API Document
  version: version1.0
paths:
  /test/:
    get:
      consumes:
      - application/x-json-stream
      description: test api detail
      parameters:
      - description: not require
        in: query
        name: none
        type: string
      responses: {}
swagger: "2.0"
