basePath: /
definitions:
  main.User:
    properties:
      age:
        example: 20
        type: integer
      id:
        example: 1
        type: integer
      name:
        example: test
        type: string
    type: object
  main.UsersResponse:
    properties:
      users: {}
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API supporter
    url: http://www.swagger.io/support
  description: API Document practice
  license:
    name: license
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: Document content
  title: Golang Swagger API Document
  version: version1.0
paths:
  /users:
    get:
      consumes:
      - application/json
      description: return users
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: age
        in: query
        name: age
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/main.UsersResponse'
            - properties:
                users:
                  items:
                    $ref: '#/definitions/main.User'
                  type: array
              type: object
      tags:
      - users
swagger: "2.0"
