// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MainUpdateUserRequest main update user request
//
// swagger:model main.UpdateUserRequest
type MainUpdateUserRequest struct {

	// age
	// Example: 21
	Age int64 `json:"age,omitempty"`

	// name
	// Example: test-name
	Name string `json:"name,omitempty"`
}

// Validate validates this main update user request
func (m *MainUpdateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this main update user request based on context it is used
func (m *MainUpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MainUpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MainUpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res MainUpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
