// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MainUsersResponse main users response
//
// swagger:model main.UsersResponse
type MainUsersResponse struct {

	// users
	Users interface{} `json:"users,omitempty"`
}

// Validate validates this main users response
func (m *MainUsersResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this main users response based on context it is used
func (m *MainUsersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MainUsersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MainUsersResponse) UnmarshalBinary(b []byte) error {
	var res MainUsersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
