// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MainCreateUserRequest main create user request
//
// swagger:model main.CreateUserRequest
type MainCreateUserRequest struct {

	// age
	// Example: 20
	Age int64 `json:"age,omitempty"`

	// name
	// Example: test
	Name string `json:"name,omitempty"`
}

// Validate validates this main create user request
func (m *MainCreateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this main create user request based on context it is used
func (m *MainCreateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MainCreateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MainCreateUserRequest) UnmarshalBinary(b []byte) error {
	var res MainCreateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
