// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MainUser main user
//
// swagger:model main.User
type MainUser struct {

	// age
	// Example: 20
	Age int64 `json:"age,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// name
	// Example: test
	Name string `json:"name,omitempty"`
}

// Validate validates this main user
func (m *MainUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this main user based on context it is used
func (m *MainUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MainUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MainUser) UnmarshalBinary(b []byte) error {
	var res MainUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
